### ISSUE TITLE
Can you port this also in spigot?

### ISSUE THREAD

**Issue by sgdc3** [games647/HealthName#1]

**Comment by TuxCoding** [comment]
:smile: 

But there are already similar plugins for Spigot like [HealthBar](http://dev.bukkit.org/bukkit-plugins/health-bar/)

**Comment by sgdc3** [comment]
It doesn't support 1.8.3+ I remember :/

**Comment by sgdc3** [comment]
I know the developer (@filoghost)

**Comment by TuxCoding** [comment]
The comments on the project page say that it does work on 1.8.

**Comment by sgdc3** [comment]
Are you shure it works with 1.8.8 clients?

**Comment by sgdc3** [comment]
I'm sure that the project is discontinued...

**Comment by TuxCoding** [comment]
It doesn't look so.

**Comment by sgdc3** [comment]
Last update was in 2014

**Comment by sgdc3** [comment]
Ok it works again since 1.8.7 :)

**Comment by TuxCoding** [comment]
Then I close this.

**Comment by sgdc3** [comment]
right sorry i was from mobile :)
